package com.liquidpixel.main.utils;

import com.badlogic.ashley.core.ComponentMapper;
import com.liquidpixel.core.components.core.PositionComponent;
import com.liquidpixel.core.components.core.StatusComponent;
import com.liquidpixel.main.components.*;
import com.liquidpixel.item.components.SpectralPickupComponent;
import com.liquidpixel.main.components.agent.AgentComponent;
import com.liquidpixel.main.components.agent.AgentJobComponent;
import com.liquidpixel.main.components.agent.WorkerComponent;
import com.liquidpixel.main.components.ai.BehaviorComponent;
import com.liquidpixel.pathfinding.components.MovementTaskComponent;
import com.liquidpixel.pathfinding.components.TraverseComponent;
import com.liquidpixel.main.components.ai.actions.DoWorkComponent;
import com.liquidpixel.main.components.animation.AnimationStoppedComponent;
import com.liquidpixel.main.components.camera.CameraComponent;
import com.liquidpixel.main.components.colony.BuildingComponent;
import com.liquidpixel.main.components.colony.EnterDoorComponent;
import com.liquidpixel.main.components.colony.ExitDoorComponent;
import com.liquidpixel.main.components.colony.HouseComponent;
import com.liquidpixel.main.components.items.*;
import com.liquidpixel.main.components.items.ResourceComponent;
import com.liquidpixel.main.components.player.CarryComponent;
import com.liquidpixel.main.components.render.FadeComponent;
import com.liquidpixel.main.components.render.RenderComponent;
import com.liquidpixel.main.components.render.ShaderComponent;
import com.liquidpixel.main.components.selection.SelectableEntityComponent;
import com.liquidpixel.main.components.selection.SelectedComponent;
import com.liquidpixel.main.components.sprite.*;
import com.liquidpixel.main.components.storage.ConsumerComponent;
import com.liquidpixel.main.components.storage.ProviderComponent;
import com.liquidpixel.main.components.storage.StorageComponent;
import com.liquidpixel.main.components.storage.StorageTileComponent;
import com.liquidpixel.main.components.ui.MarkComponent;
import com.liquidpixel.main.components.workshop.JobComponent;
import com.liquidpixel.main.components.workshop.WorkshopComponent;
import com.liquidpixel.item.components.ItemComponent;
import com.liquidpixel.sprite.components.AnimableSpriteComponent;
import com.liquidpixel.sprite.components.StackedSpritesComponent;

public class Mappers {
    public static final ComponentMapper<PositionComponent> position = ComponentMapper.getFor(PositionComponent.class);
    public static final ComponentMapper<HarvestableComponent> harvest = ComponentMapper.getFor(HarvestableComponent.class);
    public static final ComponentMapper<RenderComponent> render = ComponentMapper.getFor(RenderComponent.class);
    public static final ComponentMapper<StatusComponent> status = ComponentMapper.getFor(StatusComponent.class);
    public static final ComponentMapper<BodyComponent> body = ComponentMapper.getFor(BodyComponent.class);
    public static final ComponentMapper<AnimableSpriteComponent> animableSprite = ComponentMapper.getFor(AnimableSpriteComponent.class);
    public static final ComponentMapper<StackedSpritesComponent> stackedSprites = ComponentMapper.getFor(StackedSpritesComponent.class);
    public static final ComponentMapper<VelocityComponent> velocity = ComponentMapper.getFor(VelocityComponent.class);
    public static final ComponentMapper<EquipableComponent> equipable = ComponentMapper.getFor(EquipableComponent.class);
    public static final ComponentMapper<ItemComponent> item = ComponentMapper.getFor(ItemComponent.class);
    public static final ComponentMapper<PickupableComponent> pickup = ComponentMapper.getFor(PickupableComponent.class);
    public static final ComponentMapper<CarryComponent> carry = ComponentMapper.getFor(CarryComponent.class);
    public static final ComponentMapper<ShapeComponent> shape = ComponentMapper.getFor(ShapeComponent.class);
    public static final ComponentMapper<FollowComponent> follow = ComponentMapper.getFor(FollowComponent.class);
    public static final ComponentMapper<MovementTaskComponent> movetask = ComponentMapper.getFor(MovementTaskComponent.class);
    public static final ComponentMapper<TraverseComponent> traverse = ComponentMapper.getFor(TraverseComponent.class);
    public static final ComponentMapper<SelectableEntityComponent> selection = ComponentMapper.getFor(SelectableEntityComponent.class);
    public static final ComponentMapper<SelectedComponent> selected = ComponentMapper.getFor(SelectedComponent.class);
    public static final ComponentMapper<BehaviorComponent> behavior = ComponentMapper.getFor(BehaviorComponent.class);
    public static final ComponentMapper<SpectralPickupComponent> pickedup = ComponentMapper.getFor(SpectralPickupComponent.class);
    public static final ComponentMapper<StorageComponent> storage = ComponentMapper.getFor(StorageComponent.class);
    public static final ComponentMapper<TileableComponent> tileset = ComponentMapper.getFor(TileableComponent.class);
    public static final ComponentMapper<AgentComponent> agent = ComponentMapper.getFor(AgentComponent.class);
    public static final ComponentMapper<AgentJobComponent> agentjob = ComponentMapper.getFor(AgentJobComponent.class);
    public static final ComponentMapper<JobComponent> jobs = ComponentMapper.getFor(JobComponent.class);
    public static final ComponentMapper<InformationComponent> information = ComponentMapper.getFor(InformationComponent.class);
    public static final ComponentMapper<InStorageComponent> inStorage = ComponentMapper.getFor(InStorageComponent.class);
    public static final ComponentMapper<TileSelectionComponent> tileSelection = ComponentMapper.getFor(TileSelectionComponent.class);
    public static final ComponentMapper<CollisionComponent> collision = ComponentMapper.getFor(CollisionComponent.class);
    public static final ComponentMapper<FoundationComponent> foundation = ComponentMapper.getFor(FoundationComponent.class);
    public static final ComponentMapper<EntityComponent> entity = ComponentMapper.getFor(EntityComponent.class);
    public static final ComponentMapper<TerrainPaintingComponent> painter = ComponentMapper.getFor(TerrainPaintingComponent.class);
    public static final ComponentMapper<SettlementComponent> settlement = ComponentMapper.getFor(SettlementComponent.class);
    public static final ComponentMapper<ResourceComponent> resource = ComponentMapper.getFor(ResourceComponent.class);
    public static final ComponentMapper<ClickableComponent> clickable = ComponentMapper.getFor(ClickableComponent.class);
    public static final ComponentMapper<HouseComponent> house = ComponentMapper.getFor(HouseComponent.class);
    public static final ComponentMapper<HarvestProviderComponent> harvestProvider = ComponentMapper.getFor(HarvestProviderComponent.class);
    public static final ComponentMapper<ProviderComponent> provider = ComponentMapper.getFor(ProviderComponent.class);
    public static final ComponentMapper<PathComponent> path = ComponentMapper.getFor(PathComponent.class);
    public static final ComponentMapper<AssetComponent> asset = ComponentMapper.getFor(AssetComponent.class);
    public static final ComponentMapper<ConsumerComponent> consumer = ComponentMapper.getFor(ConsumerComponent.class);
    public static final ComponentMapper<WorkerComponent> worker = ComponentMapper.getFor(WorkerComponent.class);
    public static final ComponentMapper<MarkComponent> mark = ComponentMapper.getFor(MarkComponent.class);
    public static final ComponentMapper<HarvestableComponent> harvestable = ComponentMapper.getFor(HarvestableComponent.class);
    public static final ComponentMapper<DoWorkComponent> dowork = ComponentMapper.getFor(DoWorkComponent.class);
    public static final ComponentMapper<ResidentComponent> resident = ComponentMapper.getFor(ResidentComponent.class);
    public static final ComponentMapper<WorkshopComponent> workshop = ComponentMapper.getFor(WorkshopComponent.class);
    public static final ComponentMapper<StorageTileComponent> storageTile = ComponentMapper.getFor(StorageTileComponent.class);
    public static final ComponentMapper<StorageGroupComponent> storageGroup = ComponentMapper.getFor(StorageGroupComponent.class);
    public static final ComponentMapper<EquipmentComponent> equipment = ComponentMapper.getFor(EquipmentComponent.class);
    public static final ComponentMapper<TerrainItemComponent> terrainItem = ComponentMapper.getFor(TerrainItemComponent.class);
    public static final ComponentMapper<AnimationStoppedComponent> animationStopped = ComponentMapper.getFor(AnimationStoppedComponent.class);
    public static final ComponentMapper<EnterDoorComponent> enterDoor = ComponentMapper.getFor(EnterDoorComponent.class);
    public static final ComponentMapper<ExitDoorComponent> exitDoor = ComponentMapper.getFor(ExitDoorComponent.class);
    public static final ComponentMapper<DoorComponent> door = ComponentMapper.getFor(DoorComponent.class);
    public static final ComponentMapper<FadeComponent> fade = ComponentMapper.getFor(FadeComponent.class);
    public static final ComponentMapper<BuildingComponent> building = ComponentMapper.getFor(BuildingComponent.class);
    public static final ComponentMapper<ShaderComponent> shader = ComponentMapper.getFor(ShaderComponent.class);
    public static final ComponentMapper<FarmComponent> farm = ComponentMapper.getFor(FarmComponent.class);
    public static final ComponentMapper<GrowableComponent> growable = ComponentMapper.getFor(GrowableComponent.class);
    public static final ComponentMapper<CameraComponent> camera = ComponentMapper.getFor(CameraComponent.class);
}
